# Generated by Django 5.2.6 on 2025-09-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icao', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horizon_minutes', models.IntegerField(default=60)),
                ('thunderstorm_prob', models.FloatField(blank=True, null=True)),
                ('gale_wind_prob', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.airfield')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.airfield')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('wind_gust_ms', models.FloatField(blank=True, null=True)),
                ('wind_dir_deg', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.weatherstation')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='core_weathe_timesta_8a3a87_idx')],
            },
        ),
    ]
