# Generated by Django 5.2.6 on 2025-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(max_length=100)),
                ('version', models.CharField(default='v1', max_length=50)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
