# Generated by Django 5.2.6 on 2025-09-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=200, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.airfield')),
            ],
        ),
    ]
